name: unwritten
description: AI-powered narrative card game
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

  # Game Engine
  flame: ^1.32.0
  # Note: flame_riverpod removed due to riverpod version conflict
  # We'll integrate Flame with Riverpod 3.x manually when needed
  
  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # HTTP & API
  http: ^1.2.1
  dio: ^5.4.3+1

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_analytics: ^12.0.3

  # AI/ML
  tflite_flutter: ^0.11.0
  # Note: tflite_flutter_helper removed due to dependency conflicts
  # We'll implement helper functions directly as needed

  # Audio & Haptics
  audioplayers: ^6.1.0
  vibration: ^3.1.4
  
  # Utilities
  uuid: ^4.4.0
  intl: ^0.20.2
  equatable: ^2.0.5
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  async: ^2.11.0
  
  # UI & Animation
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  riverpod: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.7.1
  riverpod_generator: ^3.0.3
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  # hive_generator: ^2.0.1  # Removed due to source_gen conflict with riverpod_generator 3.0
  # Will re-add when Hive type adapters are needed (hive_generator 3.0+ required)

flutter:
  uses-material-design: true

  assets:
    # Data (only include existing directories)
    - assets/data/
    - assets/images/cards/
    - assets/images/ui/

